export XDG_CONFIG_HOME="$HOME/.config"
export PATH="$HOME/.cargo/bin:$PATH"
export UV_PYTHON="/run/current-system/sw/bin/python"
export UV_PYTHON_DOWNLOADS="never"
export PATH="/Users/kenny/.local/bin:$PATH"
. "/Users/kenny/.local/share/bob/env/env.sh"
