include ~/.config/kitty/black_metal_gorgoroth.conf
background_opacity 0.85


font_family Iosevka Term
font_size 23
text_composition_strategy legacy
modify_font cell_width 95%


enable_audio_bell no
hide_window_decorations yes
copy_on_select yes
mouse_hide_wait -1.0
confirm_os_window_close 0
placement_strategy top-left


# cursor_trail 10
# cursor_trail_decay 0.01 0.15
# cursor_trail_start_threshold 0


map super+t send_text all \x02t

map super+1 send_text all \x02\x31
map super+2 send_text all \x02\x32
map super+3 send_text all \x02\x33
map super+4 send_text all \x02\x34
map super+5 send_text all \x02\x35
map super+6 send_text all \x02\x36
map super+7 send_text all \x02\x37
map super+8 send_text all \x02\x38
map super+9 send_text all \x02\x39

map super+c send_text all \x02c
map super+d send_text all \x02x
map super+s send_text all \x02s
map super+i send_text all \x02i
map super+o send_text all \x02o
map super+h send_text all \x02h
map super+l send_text all \x02l
map super+j send_text all \x02j

map super+f send_text all \x02f
map super+shift+h send_text all \x02H
map super+shift+d send_text all \x02D
map super+shift+c send_text all \x02C
map super+shift+n send_text all \x02N
map super+shift+p send_text all \x02P
map super+shift+m send_text all \x02M
map super+shift+s send_text all \x02S
map super+shift+l send_text all \x02L
map super+shift+o send_text all \x02O

map super+p send_text all \x02p
map super+shift+w send_text all \x02W
map super+shift+g send_text all \x02G

map super+g send_text all \x02g
map super+y send_text all \x02y
map super+n send_text all \x02n

map super+shift+v send_text all \x02V

map super+r send_text all \x02r
