set -a terminal-features "tmux-256color:RGB"
set -g prefix C-b
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g status-position bottom
set -g status-justify left
set -g status-interval 5
set -g status-style "bg=default fg=default"
set -g status-left ""
set -g status-right "#(~/.config/scripts/workmode-status.sh) #(~/.config/scripts/timew-status.sh) "
set -g window-status-separator " "
set -g window-status-style "fg=colour8 bg=default"
set -g window-status-current-style "fg=colour7 bg=default bold"
set -g window-status-format "#I: #W  "
set -g window-status-current-format "#I: #W  "

bind t run "tmux neww -n timew ~/.config/scripts/time-picker.sh"
bind x kill-pane
bind i last-window
bind o switch-client -l
bind s split-window -h -l 25%
bind h swap-window -t -1 \; previous-window
bind l swap-window -t +1 \; next-window
bind-key j select-pane -t :.+

bind f run "tmux neww -n sesh ~/.config/scripts/tmux-session-dispensary.sh"
bind H run "~/.config/scripts/tmux-session-dispensary.sh ~"
bind D run "~/.config/scripts/tmux-session-dispensary.sh ~/dotfiles"
bind C run "~/.config/scripts/tmux-session-dispensary.sh ~/.config"
bind N run "~/.config/scripts/tmux-session-dispensary.sh ~/nix"
bind P run "~/.config/scripts/tmux-session-dispensary.sh ~/Projects"
bind M run "~/.config/scripts/tmux-session-dispensary.sh ~/Movies/good-videos"
bind S run "~/.config/scripts/tmux-session-dispensary.sh ~/School"
bind L run "~/.config/scripts/tmux-session-dispensary.sh ~/Music"

bind p run "tmux neww -n pdf ~/.config/scripts/open-pdf.sh"
bind W run "tmux neww -n work-mode 'bash ~/.config/scripts/work-mode.sh toggle; printf \"\\nPress enter to close... \"; read -r _'"
bind G run "~/.config/scripts/open-github.sh"

bind g neww -n "git" -S lazygit
bind y neww -n "yazi" -S yazi
bind n neww -n "news" -S newsboat

bind V copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle \; send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi u send-keys -X page-up
bind-key -T copy-mode-vi d send-keys -X page-down

bind r source-file $HOME/.config/tmux/tmux.conf \; display-message "Config reloaded!"
