start-at-login = true
config-version = 2
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
accordion-padding = 0
default-root-container-layout = 'accordion'
after-startup-command = ['exec-and-forget sketchybar']
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

persistent-workspaces=["1","2","3","4","5","6"]

[mode.main.binding]
alt-a = 'exec-and-forget $HOME/.config/scripts/aerospace-fixer.sh net.kovidgoyal.kitty 1'
alt-b = 'exec-and-forget $HOME/.config/scripts/aerospace-fixer.sh org.mozilla.firefox 2'
alt-d = 'exec-and-forget $HOME/.config/scripts/aerospace-fixer.sh dev.vencord.vesktop 3'
alt-e = 'exec-and-forget $HOME/.config/scripts/aerospace-fixer.sh net.whatsapp.WhatsApp 3'
alt-s = 'exec-and-forget $HOME/.config/scripts/aerospace-fixer.sh com.spotify.client 4'
alt-f = 'exec-and-forget $HOME/.config/scripts/aerospace-fixer.sh com.apple.finder 5'
alt-p = 'exec-and-forget $HOME/.config/scripts/aerospace-fixer.sh com.apple.Photos 5'
alt-o = 'exec-and-forget $HOME/.config/scripts/aerospace-fixer.sh md.obsidian 6'
alt-v = 'exec-and-forget $HOME/.config/scripts/aerospace-fixer.sh com.obsproject.obs-studio 7'
alt-g = 'exec-and-forget $HOME/.config/scripts/aerospace-fixer.sh com.figma.Desktop 8'
alt-n = 'exec-and-forget $HOME/.config/scripts/aerospace-fixer.sh me.proton.authenticator 9'

# hold ctrl before selecting to copy to clip
alt-shift-s = 'exec-and-forget screencapture -i -p'

alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

alt-t = 'layout tiles'
alt-w = 'layout accordion'
alt-shift-space = 'layout floating tiling'

alt-r = 'reload-config'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

[gaps]
outer.top = 0
outer.bottom = 0
outer.left = 0
outer.right = 0
inner.horizontal = 0
inner.vertical = 0
