add_newline = false
format = "$git_branch$directory$character"

[directory]
truncation_length = 5
truncate_to_repo = false
style = "blue"

[git_branch]
format = "[$branch]($style) "

[character]
success_symbol = '[\$](bold white)'
error_symbol = '[\$](bold white)'
vicmd_symbol = '[V](bold yellow)'
