format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character
"""

[directory]
style = "4"

[git_branch]
format = "[git:$branch]($style)"
style = "8"

[git_status]
format = "[$all_status]($style)"
style = "8"
ahead = ""
behind = ""
stashed = ""
modified = "*" # i only care about this one
staged = ""
renamed = ""
deleted = ""
untracked = ""
conflicted = ""

[character]
format = "$symbol "
success_symbol   = "[λ](4)"
error_symbol   = "[λ](4)"
vicmd_symbol   = "[λ](bold 1)"
