require("utils.buildhooks")

require("plugins.devicons")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.mini")
require("plugins.bufferline")
require("plugins.builtin")
require("plugins.cmp")
require("plugins.statusline")
require("plugins.noice")
require("plugins.gitsigns")
