;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from my-lib-modeline.el

(register-definition-prefixes "my-lib-modeline" '("my-modeline-"))


;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
