#+title: GNU Emacs Configuration
#+author: Kenneth Xu
#+language: en-gb
#+options: ':t toc:nil num:t author:t email:t
#+startup: content indent

This is my literate configuration for GNU Emacs. It uses ~org-babel~, a package which allows for the use of written text alongside blocks of code.
My configuration is heavily inspired by Protesilaos, an Emacs package maintainer and content creator. It is likely you will see some parallels between my configuration and his.
*You can check my [[https://github.com/kxu111/dotfiles][dotfiles]] to see what OS and build of Emacs I am using*.

Usually, people use their =init.el= to call the command ~org-babel-load-file~ in order to load their literate configuration. However, I believe this method is ineffective because using it forces us to load Org before starting Emacs. Instead, I will make use of this command:

#+begin_src emacs-lisp :tangle no :results none
(org-babel-tangle)
#+end_src

The command ~org-babel-tangle~ (bound to =C-c C-v C-t=), takes the blocks of code from inside your configuration and deploys them inside of standalone files. That way, you can write all of your configuration inside one literate configuration file, but you don't have to deal with the inefficiency that comes with being forced to start Emacs from an Org file.

~org-babel~ allows you to have a modular configuration while also being able to manage everything from one place. This has many advantages. For example, you can continue treating a singular file as the "root" of your configuration, however if somebody wishes to see a know how you accomplished something, you need only send them the relevant files, as opposed to sending them your entire configuration.
Additionally, if you weren't convinced already, you also gain access a whole host of the advantages that come with working with Org files, for example the ability to export your configuration as a PDF or website.

* The anatomy of an Emacs configuration

The current Org file is not loaded on Emacs' startup. Rather, it generates the files that Emacs will read. Here is a list of the files that this Org file will generate:

- Standard file =early-init.el= :: Configures the Emacs frame and defines the behaviour of Emacs in its loading phase.

- Standard file =init.el= :: This sets up some lisp macros, runs some fixes (e.g disabling the custom file) and loads the configuration modules.

* The package manager (=straight.el=)

I use =straight.el= thanks to its ability to create lockfiles.
=straight.el='s Github: <https://github.com/radian-software/straight.el>

** The =early-init.el= disables package in favour of =straight.el=

#+begin_src emacs-lisp :tangle "early-init.el"
;; Disable package in favour of "straight.el".
(setq package-enable-at-startup nil)
#+end_src

** The =init.el= bootstraps =straight.el=

#+begin_src emacs-lisp :tangle "init.el"
;; Bootstrap "straight.el"
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
#+end_src

** The =init.el= configures =straight.el=

#+begin_src emacs-lisp :tangle "init.el"
(use-package straight
  :custom
  (straight-use-package-by-default t)
  (straight-current-profile 'base)
  (straight-vc-git-default-protocol 'ssh)
  :config
  (setq straight-profiles
        `((base . "~/dotfiles/.emacs.d/straight.lockfile.base.el")
          (programming . "~/dotfiles/.emacs.d/straight.lockfile.programming.el"))))
#+end_src

* The early initialisation of Emacs (=early-init.el=)

** The =early-init.el= basic frame settings

Keep in mind ~frame-resize-pixelwise~ and ~frame-inhibit-implied-resize~ are important; without it, Emacs will use strange frame sizes and resize the frame if you adjust the font size.

#+begin_src emacs-lisp :tangle "early-init.el"
(setq frame-resize-pixelwise t
      frame-inhibit-implied-resize 'force
      frame-title-format '("%b")
      ring-bell-function 'ignore
      use-short-answers t
      inhibit-startup-screen t
      inhibit-startup-echo-area-message user-login-name ; Disable the message in the minibuffer on Emacs start.
      )

(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)
(blink-cursor-mode -1)
#+end_src

** The =early-init.el= set frame parameters and variables based on platform

Here I set options based on what platform I am using, such as rebinding keys, or modifying the aesthetics of the frame.

When I use MacOS, I am using [[https://github.com/d12frosted/homebrew-emacs-plus][Emacs Plus]].

Keep in mind that ~initial-frame-alist~ only affects the first frame while ~default-frame-alist~ affects all future frames.

#+begin_src emacs-lisp :tangle "early-init.el"
(add-to-list 'initial-frame-alist '(fullscreen . maximized))

;; MacOS options
(when (eq system-type 'darwin)
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (setq mac-left-command-modifier 'meta
        mac-option-modifier nil))
#+end_src

** The =early-init.el= tweaks to startup time and garbage collection

This is code copied from Protesilaos' configuration. In this snippet, he raises some variables to high values until Emacs loads, at which point he lowers them to a more practical amount.

#+begin_src emacs-lisp :tangle "early-init.el"
;; Temporarily increase the garbage collection threshold.  These
;; changes help shave off about half a second of startup time.  The
;; `most-positive-fixnum' is DANGEROUS AS A PERMANENT VALUE.  See the
;; `emacs-startup-hook' a few lines below for what I actually use.
(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 0.5)

;; Same idea as above for the `file-name-handler-alist' and the
;; `vc-handled-backends' with regard to startup speed optimisation.
;; Here I am storing the default value with the intent of restoring it
;; via the `emacs-startup-hook'.
(defvar prot-emacs--file-name-handler-alist file-name-handler-alist)
(defvar prot-emacs--vc-handled-backends vc-handled-backends)

(setq file-name-handler-alist nil
      vc-handled-backends nil)

(add-hook 'emacs-startup-hook
          (lambda ()
            (setq gc-cons-threshold (* 100 100 8)
                  gc-cons-percentage 0.1
                  file-name-handler-alist prot-emacs--file-name-handler-alist
                  vc-handled-backends prot-emacs--vc-handled-backends)))
#+end_src

** The =early-init.el= makes loading frame match theme

Make the initial frame match your theme's background colors.

#+begin_src emacs-lisp :tangle ./early-init.el
(defun prot-emacs-re-enable-frame-theme (_frame)
  (when-let* ((theme (car custom-enabled-themes)))
    (enable-theme theme)))

;; Make the initial frame match your theme's background colors.
(defun prot-emacs-avoid-initial-flash-of-light ()
  (setq mode-line-format nil)
  (set-face-attribute 'default nil :background "#000000" :foreground "#ffffff")
  (set-face-attribute 'mode-line nil :background "#000000" :foreground "#ffffff" :box 'unspecified)
  (add-hook 'after-make-frame-functions #'prot-emacs-re-enable-frame-theme))

(prot-emacs-avoid-initial-flash-of-light)
#+end_src

** The =early-init.el= sets the ~user-lisp-directory~

The ~user-lisp-directory~ is a user option introduced in Emacs 31. It makes Emacs byte compile Emacs Lisp files therein and scan them for autoloads.

#+begin_src emacs-lisp :tangle "early-init.el"
(setq user-lisp-directory (locate-user-emacs-file "my-libs/"))
#+end_src


* The main initialisation of Emacs (=init.el=)

** The =init.el= tweaks to make native compilation silent

Native compilation helps speed up Emacs by translating Emacs Lisp down to machine code. However, it has an annoying habit of displaying verbose errors which usually don't mean anything *to the average user*.

#+begin_src emacs-lisp :tangle "init.el"
;; Make native compilation silent.
(when (native-comp-available-p)
  (setq native-comp-async-report-warnings-errors 'silent))
#+end_src

** The =init.el= obliviates the custom file

The custom file is an absolutely useless feature of Emacs that contributes very little to my configuration, if at all. This is because I use =straight.el= to manage my installed packages (something the custom file usually does) and you can set =custom-safe-themes= to =t=, removing the need to track what themes are trusted. And finally, if you use =M-x customize=, you're probably a psychopath.

This code works by sending the custom file to the =/tmp= directory, which is automatically cleared when you close your computer. Additionally, the file is never loaded, effectively removing it from existence.

#+begin_src emacs-lisp :tangle "init.el"
;; Disable the custom file by sending it to the temporary directory.
(setq custom-file (make-temp-file "emacs-custom-"))
#+end_src

** The =init.el= option to declare all themes as safe

Marks all themes as safe. I trust the devs :)
As a precaution, don't try lesser-known packages before vetting the code.

#+begin_src emacs-lisp :tangle "init.el"
(setq custom-safe-themes t)
#+end_src

** The =init.el= macro to configure a package (~my-emacs-configure~)

The ~my-emacs-configure~ is a simple wrapper around ~condition-case~. The idea is to add arbitrary code for the configuration of a given package and catch any errors so that Emacs can still load without that package's code.

#+begin_src emacs-lisp :tangle "init.el"
(defmacro my-emacs-configure (&rest body)
  "Evaluate BODY and catch any errors."
  (declare (indent 0))
  `(condition-case err
       (progn ,@body)
     ((error user-error quit)
      (message "Failed to configure package starting with `%S' because of `%S'" (car ',body) (cdr err)))))
#+end_src


** The =init.el= loading of my modules and libraries

#+begin_src emacs-lisp :tangle "init.el"
(mapc
 (lambda (string)
   (add-to-list 'load-path (locate-user-emacs-file string)))
 '("my-libs" "my-modules"))
#+end_src

** The =init.el= final part to source the modules

I'm going to use Protesilaos as a reference once again and split my configuration into multiple files.

Splitting into multiple files allows me to review the individual source code files rather than searching through a large Org file.

#+begin_src emacs-lisp :tangle "init.el"
(require 'my-emacs-theme)
(require 'my-emacs-prog-mode)
(require 'my-emacs-git)
#+end_src

* The modules of my configuration (=my-modules/=)

** The =my-emacs-theme.el= module

*** TODO Implement theme picker

- Make it so you can change fonts on theme switch
- Add custom overrides for each theme

*** The =my-emacs-theme.el= section to load themes

*Some Favourite Themes*:
- doric-dark
- doom-dark+
- doric-light

#+begin_src emacs-lisp :tangle "my-modules/my-emacs-theme.el"
(use-package doric-themes)
(load-theme doric-light)
#+end_src

*** The =my-emacs-theme.el= section to load fonts

*Favourite Fonts*:
- =Iosevka=
- =Aporetic Sans/Serif Mono=
- =IBM Plex Mono=

#+begin_src emacs-lisp :tangle "my-modules/my-emacs-theme.el"
(set-face-font 'default "Aporetic Sans Mono 20")
(set-face-font 'fixed-pitch "Aporetic Sans Mono 20")
(set-face-font 'variable-pitch "Aporetic Sans 20")
#+end_src

*** The =my-emacs-theme.el= section to call to provide

#+begin_src emacs-lisp :tangle "my-modules/my-emacs-theme.el"
(provide 'my-emacs-theme)
#+end_src

** The =my-emacs-prog.el= module

This module is to configure packages and parameters relevant to ~prog-mode~.

*When installing programming modes, use ~:defer t~ to avoid them loading preemptively.* I don't know if this does anything, but it's good to be safe.

*** The =my-emacs-prog-mode.el= section for ~eglot~

~Eglot~ is a client for using LSP (Language Server Protocol) servers. I prefer it over ~lsp-mode~ because it is more lightweight and makes use of builtin Emacs features rather than implementing its own.

#+begin_src emacs-lisp :tangle "my-modules/my-emacs-prog-mode.el"
(use-package eglot
  :bind
  (:map eglot-mode-map
        ("C-c l a" . eglot-code-actions)
        ("C-c l r" . eglot-rename)
        ("C-c l f" . eglot-format)))
#+end_src

To enable an ~eglot~ for a specific mode, add the following to your configuration. Of course, you must have a supported language server installed first, but that's out of scope for this.

#+begin_example emacs-lisp
(add-hook SAMPLE-mode-hook . eglot-ensure)
#+end_example

*** The =my-emacs-prog-mode.el= section for ~c++-mode~

#+begin_src emacs-lisp :tangle "my-modules/my-emacs-prog-mode.el"
;; c++ mode is built in
(add-hook c++-mode-hook . eglot-ensure)
#+end_src

*** The =my-emacs-prog-mode.el= section for ~nix-mode~

#+begin_src emacs-lisp :tangle "my-modules/my-emacs-prog-mode.el"
(use-package nix-mode :defer t)
(add-hook nix-mode-hook . eglot-ensure)
#+end_src

*** The =my-emacs-prog-mode.el= to call to provide

#+begin_src emacs-lisp :tangle "my-modules/my-emacs-prog-mode.el"
(provide my-emacs-prog-mode)
#+end_src

** The =my-emacs-git.el= module

*** The =my-emacs-git.el= section to for =vc.el=

VC refers to "version control", which is what allows you to track your files and visualise changes across different versions of your data.

#+begin_src emacs-lisp :tangle "my-modules/my-emacs-git.el"
(my-emacs-configure
 (setq vc-follow-symlinks t)

 (with-eval-after-load 'vc
    ;; I only use Git.  If I ever need another, I will include it here.
    ;; This may have an effect on performance, as Emacs will not try to
    ;; check for a bunch of backends.
    (setq vc-handled-backends '(Git))

    (setq vc-dir-save-some-buffers-on-revert t))
#+end_src

*** The =prot-emacs-git.el= section to for ~magit~

Magit is an amazing package. It can basically do everything the builtin =vc.el= can do, and that's with no setup.
Start by pressing =C-x g= (~magit-status~) to bring up the state of the repository.

#+begin_src emacs-lisp :tangle "my-modules/my-emacs-git.el"
(use-package magit)
#+end_src

*** The =my-emacs-git.el= section call to provide

#+begin_src emacs-lisp :tangle "my-modules/my-emacs-git.el"
(provide 'my-emacs-git)
#+end_src

* TODO Transfer the legacy config

** Enable Useful Modes

#+begin_src emacs-lisp
  (delete-selection-mode t) ; Typing while a selection is active automatically replaces it with what you typed.
  (global-auto-revert-mode t) ; Emacs refreshes a file once it changes on disk.
  (savehist-mode t) ; Save minibuffer history.
  (which-key-mode t)
#+end_src

** Keybind Overrides

Inspired by the following video: [[https://youtu.be/D99GB591Vgo][Emacs: Global Keybinding Overrides - Protesilaos]]

#+begin_src emacs-lisp
  (defvar my-overrides-mode-map (make-sparse-keymap)
    "Keymap for `my-overrides-mode'.")

  (define-minor-mode my-overrides-mode
    "Activate `my-overrides-mode-map'."
    :global t
    :init-value nil
    :keymap my-overrides-mode-map)

  (define-key my-overrides-mode-map
              (kbd "C-,")
              (lambda ()
                (interactive)
                (duplicate-line)
                (next-line)))

  (my-overrides-mode t) ; I just re-enable this every time I define a keybind
#+end_src

** Global Hooks

#+begin_src emacs-lisp
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+end_src

** Modeline

*** Mode Icons

These functions are mostly taken from Protesilaos' config.

#+begin_src emacs-lisp
  (defvar my-mode-icons
    '((dired-mode   "")
      (archive-mode "🮯")
      (diff-mode    "⇄")
      (prog-mode    "λ")
      (conf-mode    "")
      (text-mode    "¶")
      (comint-mode  "⨠")
      (t            "·")))

  (defun my-mode-line-icon ()
    (or
     (cadr (assq major-mode my-mode-icons))
     (catch 'icon
       (dolist (entry my-mode-icons)
         (when (and (not (eq (car entry) t)) (derived-mode-p (car entry)))
           (throw 'icon (cadr entry)))))
     (cadr (assq t my-mode-icons))))

  ;; These blocks check if Emacs can display a sufficient amount of colors, and then checks if the theme is light or dark
  (defface my-icons-red
    '((((class color) (min-colors 88) (background light)) :foreground "#aa3232")
      (((class color) (min-colors 88) (background dark)) :foreground "#f06464")
      (t :foreground "red"))
    "Use for red-colored icons")

  (defface my-icons-gray
    '((t :inherit (bold shadow)))
    "Use for gray-colored icons.")
#+end_src

*** Modeline Components

- ~my-mode-line-buffer-name~: If the current buffer is unsaved, the buffer name goes italic.
- ~my-mode-line-vc-mode~: Displays version control icon and branch. If the current file is under version control and is modified, the branch name becomes italic.

#+begin_src emacs-lisp
  (defvar my-modeline-read-only
    '(:eval
      (when buffer-read-only
        (propertize
         " "
         'face (if (mode-line-window-selected-p)
                   'my-icons-red
                 'my-icons-gray)))))

  (defvar my-modeline-buffer-name
    '(:eval
      (propertize (buffer-name) 'face
                  (if (buffer-modified-p)
                      '(:weight bold :slant italic) 'bold))))

  (defvar my-modeline-major-mode
    '(:eval
      (format "%s %s"
              (propertize (my-mode-line-icon) 'face 'my-icons-gray)
              (capitalize (string-replace "-mode" "" (symbol-name major-mode))))))

  (defvar my-modeline-vc
    '(:eval
      (when (mode-line-window-selected-p)
        (unless (not vc-mode)
          (let ((s (substring-no-properties vc-mode 5)))
            (concat
             (propertize "⇅ " 'face 'my-icons-gray)
             (if (eq (vc-state buffer-file-name) 'up-to-date)
                 s
               (propertize s 'face 'italic))))))))

  (defvar my-modeline-multiple-cursors
    '(:eval
      (when (and (mode-line-window-selected-p) (bound-and-true-p multiple-cursors-mode))
        mc/mode-line)))

  (defvar my-modeline-position
    '(:eval
      (when (mode-line-window-selected-p)
        (format-mode-line "%6l:%c (%%p)"))))

  (setq display-time-string-forms '((format-time-string "%a %d %b, %H:%M")))
  (display-time-mode t)
  (defvar my-modeline-misc-info
    '(:eval
      (when (mode-line-window-selected-p)
        (format-mode-line mode-line-misc-info))))
#+end_src

*** Modeline Format

#+begin_src emacs-lisp
  (setq-default mode-line-format
                (list
                 "  %e"
                 my-modeline-read-only
                 my-modeline-buffer-name
                 "  "
                 my-modeline-major-mode
                 'mode-line-process
                 "  "
                 my-modeline-vc
                 'mode-line-format-right-align
                 my-modeline-multiple-cursors
                 my-modeline-position
                 "  "
                 my-modeline-misc-info
                 "  "))
#+end_src

** Base Packages

*** Text Manipulation

#+begin_src emacs-lisp
  (use-package multiple-cursors
    :custom
    (mc/always-run-for-all t)
    :config
    (define-key my-overrides-mode-map (kbd "C-M-j") #'mc/mark-all-dwim)
    (define-key my-overrides-mode-map (kbd "C-M-/") #'mc/mark-all-like-this)

    (define-key my-overrides-mode-map (kbd "C-M-,") #'mc/mark-previous-like-this)
    (define-key my-overrides-mode-map (kbd "C-M-.") #'mc/mark-next-like-this)

    (define-key my-overrides-mode-map (kbd "C-<") #'mc/skip-to-previous-like-this)
    (define-key my-overrides-mode-map (kbd "C->") #'mc/skip-to-next-like-this)

    (define-key my-overrides-mode-map (kbd "C-M-c") #'mc/edit-lines)
    (define-key my-overrides-mode-map (kbd "C-M-n") #'mc/insert-numbers)
    (define-key my-overrides-mode-map (kbd "C-M-'") #'mc-hide-unmatched-lines-mode))

  (use-package expreg
    :config
    (define-key my-overrides-mode-map (kbd "C-M-l") #'expreg-expand)
    (define-key my-overrides-mode-map (kbd "C-M-h") #'expreg-contract))

  (use-package move-text
    :config
    (define-key my-overrides-mode-map (kbd "M-p") #'move-text-up)
    (define-key my-overrides-mode-map (kbd "M-n") #'move-text-down))

  (my-overrides-mode t)
#+end_src

*** Org-Mode

#+begin_src emacs-lisp
  (use-package org
    :straight (:host github :repo "bzg/org-mode" :branch "main")
    :hook (org-mode . visual-line-mode)
    :custom
    (org-use-speed-commands t)
    (org-startup-indented t)
    (org-hide-emphasis-markers t)
    (org-cycle-separator-lines 1) ; Keep a line between folded headings
    (org-src-content-indentation 0)
    :config
    (require 'org-tempo)
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("sh" . "src shell"))

    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t)
       (shell . t))))

  (use-package org-roam
    :bind
    ("C-c n c" . org-roam-capture)
    ("C-c n f" . org-roam-node-find)
    ("C-c n i" . org-roam-node-insert)
    :custom (org-capture-bookmark nil)
    :config (org-roam-db-autosync-mode t))

  (use-package org-roam-ui :commands org-roam-ui-mode)
#+end_src

*** Completions

#+begin_src emacs-lisp
  (use-package vertico
    :config
    (vertico-mode)
    (vertico-multiform-mode)
    :custom
    (vertico-multiform-commands ; Customize display per-command
     '((execute-extended-command flat)))
    (vertico-resize t)
    (vertico-count 12))

  (use-package consult
    :bind
    ("M-s M-g" . consult-ripgrep)
    ("M-s M-f" . find-file)
    ("M-s M-d" . consult-fd) ; Mnemonic: Search Directory
    ("M-s M-o" . consult-outline)
    ("M-s M-l" . consult-line)
    ("M-s M-b" . consult-buffer)
    ("M-s M-k" . kill-buffer)

    :config
    (setq consult-ripgrep-args "rg --null --line-buffered --color=never --max-columns=1000 --path-separator / --smart-case --no-heading --with-filename --line-number --search-zip --hidden"
          consult-fd-args "fd --full-path --color=never --hidden")

    ;; Don't display these buffers
    (let ((buffers '("*Async-native-compile-log*" "*straight-process*" "*straight-byte-compilation*" "*direnv*" "*Messages*" "*Help*" "*Backtrace*" "*Warnings*" "*Native-compile-Log" "*elfeed-tube-log*")))
      (dolist (buf buffers) (add-to-list 'consult-buffer-filter (regexp-quote buf))))
    (add-to-list 'consult-buffer-filter "\\*EGLOT.*\\*")
    (add-to-list 'consult-buffer-filter "magit.*:"))

  (use-package marginalia :config (marginalia-mode))

  (use-package orderless :config (setq completion-styles '(orderless basic)))

  (use-package embark
    :bind
    ("C-." . embark-act)
    (:map minibuffer-local-map
          ("C-c C-c" . embark-collect)
          ("C-c C-e" . embark-export)))

  (use-package embark-consult)

  (use-package corfu
    :custom
    (corfu-count 6)
    (corfu-auto-prefix 2)
    :init
    (global-corfu-mode)
    (corfu-popupinfo-mode)
    :hook (prog-mode . (lambda () (setq-local corfu-auto t)))
    :bind (:map corfu-map ("M-SPC" . corfu-insert-separator)))
#+end_src

*** wgrep
#+begin_src emacs-lisp
  (use-package wgrep
    :bind
    (:map grep-mode-map
          ("e" . wgrep-change-to-wgrep-mode)
          ("C-x C-q" . wgrep-change-to-wgrep-mode)
          ("C-c C-c" . wgrep-finish-edit))
    (:map compilation-mode-map
          ("e" . wgrep-change-to-wgrep-mode)
          ("C-x C-q" . wgrep-change-to-wgrep-mode)
          ("C-c C-c" . wgrep-finish-edit)))
#+end_src

*** Split Navigation

#+begin_src emacs-lisp
  (use-package golden-ratio
    :config
    (golden-ratio-mode t)
    (add-to-list 'golden-ratio-extra-commands 'ace-window))

  (use-package ace-window :config (define-key my-overrides-mode-map (kbd "M-o") #'ace-window))

  (my-overrides-mode t)
#+end_src

*** Elfeed

#+begin_src emacs-lisp
  (use-package elfeed
    :bind ("C-x f" . elfeed)
    :hook (elfeed-show-mode . visual-line-mode)
    :custom (elfeed-search-filter "@6months +unread -junk"))

  (use-package elfeed-org
    :after elfeed
    :config (elfeed-org)
    :custom (rmh-elfeed-org-files (list "~/.emacs.d/Emacs.org")))

  (use-package elfeed-tube
    :after elfeed
    :bind
    (:map elfeed-show-mode-map
          ("F" . elfeed-tube-fetch)
          ([remap save-buffer] . elfeed-tube-save))
    (:map elfeed-search-mode-map
          ("F" . elfeed-tube-fetch)
          ([remap save-buffer] . elfeed-tube-save))
    :config
    (elfeed-tube-setup)
    (add-hook 'elfeed-new-entry-hook
              (elfeed-make-tagger :entry-link "https://www\\.youtube\\.com/shorts/.*"
                                  :add 'junk
                                  :remove 'unread)))

  (use-package mpv)

  (use-package elfeed-tube-mpv
    :after elfeed
    :bind
    (:map elfeed-show-mode-map
          ("<return>" . elfeed-tube-mpv)
          ("C-c C-f" . elfeed-tube-mpv-follow-mode)
          ("C-c C-w" . elfeed-tube-mpv-where)))
#+end_src



** RSS Feeds

*** Info

**** Tagging Rules

- Two main sections, one for blogs, and the other for videos.
  - =Videos= is not exclusive to YouTube content.
- If a feed contains neither blog nor video, it is placed under the heading =Misc=.
  - The reason we do not tag the feed with both ~:blog:~ and ~:video:~ is because if I am searching for blogs, under no circumstances do I  want to see any video content, and vice versa.
- Mark important feeds with ~:mustread:~.
- Mark discontinued feeds with ~:archived:~.

**** Script to find YouTube feeds (requires curl)

*Link channels here (in a ~|table|~, with "quotation marks"):*

#+NAME: channels
| "https://youtube.com/@protesilaos" |

*Press =C-c C-c= on this:*
#+begin_src shell :var channels=channels :results raw
#!/usr/bin/env bash

extract_rss_info() {
    local youtube_channel_url="$1"

    local page
    page=$(curl -Ls "$youtube_channel_url")

    local channel_id
    channel_id=$(echo "$page" |
                     sed -n 's/.*"externalId":"\(UC[^"]*\)".*/\1/p' |
                     head -n1)

    local display_name
    display_name=$(echo "$page" |
                       sed -n 's/.*"channelMetadataRenderer":{"title":"\([^"]*\)".*/\1/p' |
                       head -n1)

    if [[ -n "$channel_id" && -n "$display_name" ]]; then
        echo "[[https://www.youtube.com/feeds/videos.xml?channel_id=$channel_id][$display_name]]"
    else
        echo "Failed to extract data for $youtube_channel_url"
    fi
}

while IFS= read -r url; do
    extract_rss_info "$url"
done <<< "$channels"
#+end_src

#+RESULTS:
[[https://www.youtube.com/feeds/videos.xml?channel_id=UC0uTPqBCFIpZxlz_Lv1tk_g][Protesilaos]]

*** Feeds                                                            :elfeed:

**** Blogs                                                             :blog:
***** [[https://blog.andymatuschak.org/rss][Andy Matuschak: Square Signals]] :archived:
***** [[https://usefulfictions.substack.com/feed][Useful Fictions]] :mustread:
***** [[https://kamilkazani.substack.com/feed][kamilkanazi]]       :mustread:

**** Video                                                            :video:
***** [[https://www.youtube.com/feeds/videos.xml?channel_id=UC04nROIJrY22Gl2aFqKcdqQ][Vimothee]] :mustread:
***** [[https://vimothee.substack.com/feed][Vimothee RSS]]         :mustread:
***** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCkfuek_fQ18a9W1Hk9ntwug][Vimothee's Vestibule]] :mustread:
***** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCsO-2AVa4SJXS30gnqMjv-A][No-Am]] :mustread:

***** Education                                                         :edu:
****** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q][Kurzgesagt – In a Nutshell]]
****** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCq8ZAAsI89IoJ-fn1gYpO3g][Nightshift – Kurzgesagt After Dark]]
****** [[https://www.youtube.com/feeds/videos.xml?channel_id=UC2C_jShtL725hvbm1arSV9w][CGP Grey]] :mustread:
****** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCTpmmkp1E4nmZqWPS-dl5bg][Quanta Magazine]]

***** Emacs                                                      :emacs:code:
****** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCA5krj-yK4efs1d477A1ZLQ][Bardman]]
****** [[https://www.youtube.com/feeds/videos.xml?channel_id=UC1tV5SjRyejRGeHAaMGYSsQ][Joshua Blais]]

***** Tech                                                             :tech:
****** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCcaTUtGzOiS4cqrgtcsHYWg][jvscholz]]

***** Programming                                                      :code:
****** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCgUxdfi_5-m67UDbrgcAFBg][Coding Jesus]]
****** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCwHwDuNd9lCdA7chyyquDXw][Bread on Penguins]]
****** [[https://www.youtube.com/feeds/videos.xml?channel_id=UCpwl7jNE9PJc-lBTShNs5TQ][Coding with Sphere]]
****** [[https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA][Luke Smith]]

****** Live                                                            :live:
Not exactly live streaming, just unscripted videos in general.
******* [[https://www.youtube.com/feeds/videos.xml?channel_id=UCOt3Ssxx03pxLdH3qzyTAsQ][Daniel Hirsch]]
******* [[https://www.youtube.com/feeds/videos.xml?channel_id=UCEbYhDd6c6vngsF5PQpFVWg][Tsoding]]
******* [[https://www.youtube.com/feeds/videos.xml?channel_id=UCrqM0Ym_NbK1fqeQG2VIohg][Tsoding Daily]]

**** Misc                                                              :misc:
