#+title: GNU Emacs Configuration
#+author: Kenneth Xu
#+language: en-gb
#+options: ':t toc:nil num:t author:t email:t
#+startup: content indent
#+property: header-args:emacs-lisp :mkdirp yes

This is my literate configuration for GNU Emacs. It uses ~org-babel~, a package which allows for the use of written text alongside blocks of code.
My configuration is heavily inspired by Protesilaos, an Emacs package maintainer and content creator. It is likely you will see some parallels between my configuration and his.
*You can check my [[https://github.com/kxu111/dotfiles][dotfiles]] to see what OS and build of Emacs I am using*.

Usually, people use their =init.el= to call the command ~org-babel-load-file~ in order to load their literate configuration. However, I believe this method is ineffective because using it forces us to load Org before starting Emacs. Instead, I will make use of this command:

#+begin_src emacs-lisp :tangle no :results none
(org-babel-tangle)
#+end_src

The command ~org-babel-tangle~ (bound to =C-c C-v C-t=), takes the blocks of code from inside your configuration and deploys them inside of standalone files. That way, you can write all of your configuration inside one literate configuration file, but you don't have to deal with the inefficiency that comes with being forced to start Emacs from an Org file.

~Org-babel~ allows you to have a modular configuration while also being able to manage everything from one place. This has many advantages. For example, you can continue treating a singular file as the "root" of your configuration, however if somebody wishes to see a know how you accomplished something, you need only send them the relevant files, as opposed to sending them your entire configuration.
Additionally, if you weren't convinced already, you also gain access a whole host of the advantages that come with working with Org files, for example the ability to export your configuration as a PDF or website.

* The anatomy of an Emacs configuration

The current Org file is not loaded on Emacs' startup. Rather, it generates the files that Emacs will read. Here is a list of the files that this Org file will generate:

- Standard file =early-init.el= :: Configures the Emacs frame and defines the behaviour of Emacs in its loading phase.

- Standard file =init.el= :: This sets up some Emacs Lisp macros, runs some fixes (e.g disabling the custom file) and loads the configuration modules.

- Custom folder =my-modules/= :: This contains some custom modules I defined. A module is nothing more than a group of related packages, modes, and settings.

- Custom folder =my-libraries/= :: This contains custom Emacs Lisp I write that I can use in other places of my configuration, but aren't as lightweight and commonly used as the macros in =init.lua=.

* The package manager (=straight.el=)

I use =straight.el= thanks to its ability to create lockfiles.
=straight.el='s Github: <https://github.com/radian-software/straight.el>

** The =early-init.el= disables package in favour of =straight.el=

#+begin_src emacs-lisp :tangle "early-init.el"
;; Disable package in favour of "straight.el".
(setq package-enable-at-startup nil)
#+end_src

** The =init.el= bootstraps =straight.el=

#+begin_src emacs-lisp :tangle "init.el"
;; Bootstrap "straight.el"
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

(use-package straight
  :custom
  (straight-use-package-by-default t)
  (straight-current-profile 'base)
  (straight-vc-git-default-protocol 'ssh)
  :config
  (setq straight-profiles `((base . "~/dotfiles/.emacs.d/lockfile.el"))))
#+end_src

* The early initialisation of Emacs (=early-init.el=)

** The =early-init.el= basic frame settings

Keep in mind ~frame-resize-pixelwise~ and ~frame-inhibit-implied-resize~ are important; without it, Emacs will use strange frame sizes and resize the frame if you adjust the font size.

#+begin_src emacs-lisp :tangle "early-init.el"
(setq frame-resize-pixelwise t
      frame-inhibit-implied-resize 'force
      frame-title-format '("%b")
      ring-bell-function 'ignore
      use-short-answers t
      inhibit-startup-screen t
      inhibit-startup-echo-area-message user-login-name ; Disable the message in the minibuffer on Emacs start.
      )

(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)
(blink-cursor-mode -1)
#+end_src

** The =early-init.el= set frame parameters and variables based on platform

Here I set options based on what platform I am using, such as rebinding keys, or modifying the aesthetics of the frame.

When I use MacOS, I am using [[https://github.com/d12frosted/homebrew-emacs-plus][Emacs Plus]].

Keep in mind that ~initial-frame-alist~ only affects the first frame while ~default-frame-alist~ affects all future frames.

#+begin_src emacs-lisp :tangle "early-init.el"
  (add-to-list 'initial-frame-alist '(fullscreen . maximized))

  ;; MacOS options
  (when (eq system-type 'darwin)
    (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
    (setq mac-command-modifier 'meta
  	mac-right-command-modifier 'super
          mac-option-modifier nil))
#+end_src

** The =early-init.el= tweaks to startup time and garbage collection

This is code copied from Protesilaos' configuration. In this snippet, he raises some variables to high values until Emacs loads, at which point he lowers them to a more practical amount.

#+begin_src emacs-lisp :tangle "early-init.el"
;; Temporarily increase the garbage collection threshold.  These
;; changes help shave off about half a second of startup time.  The
;; `most-positive-fixnum' is DANGEROUS AS A PERMANENT VALUE.  See the
;; `emacs-startup-hook' a few lines below for what I actually use.
(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 0.5)

;; Same idea as above for the `file-name-handler-alist' and the
;; `vc-handled-backends' with regard to startup speed optimisation.
;; Here I am storing the default value with the intent of restoring it
;; via the `emacs-startup-hook'.
(defvar prot-emacs--file-name-handler-alist file-name-handler-alist)
(defvar prot-emacs--vc-handled-backends vc-handled-backends)

(setq file-name-handler-alist nil
      vc-handled-backends nil)

(add-hook 'emacs-startup-hook
          (lambda ()
            (setq gc-cons-threshold (* 100 100 8)
                  gc-cons-percentage 0.1
                  file-name-handler-alist prot-emacs--file-name-handler-alist
                  vc-handled-backends prot-emacs--vc-handled-backends)))
#+end_src

** The =early-init.el= makes loading frame match theme

Make the initial frame match your theme's background colors.

#+begin_src emacs-lisp :tangle ./early-init.el
(defun my-emacs-re-enable-theme (_frame)
  (when-let* ((theme (car custom-enabled-themes)))
    (enable-theme theme)))

;; Make the initial frame match your theme's background colors.
(defun my-emacs-fix-start-bg ()
  (setq mode-line-format nil)
  (set-face-attribute 'default nil :background "#000000" :foreground "#ffffff")
  (set-face-attribute 'mode-line nil :background "#000000" :foreground "#ffffff" :box 'unspecified)
  (add-hook 'after-make-frame-functions #'my-emacs-re-enable-theme))

(my-emacs-fix-start-bg)
#+end_src

** The =early-init.el= sets the ~user-lisp-directory~

The ~user-lisp-directory~ is a user option introduced in Emacs 31. It makes Emacs byte compile Emacs Lisp files therein and scan them for autoloads.

#+begin_src emacs-lisp :tangle "early-init.el"
(setq user-lisp-directory (locate-user-emacs-file "my-libraries/"))
#+end_src

* The main initialisation of Emacs (=init.el=)

** The =init.el= tweaks to make native compilation silent

Native compilation helps speed up Emacs by translating Emacs Lisp down to machine code. However, it has an annoying habit of displaying verbose errors which usually don't mean anything *to the average user*.

#+begin_src emacs-lisp :tangle "init.el"
;; Make native compilation silent.
(when (native-comp-available-p)
  (setq native-comp-async-report-warnings-errors 'silent))
#+end_src

** The =init.el= obliviates the custom file

The custom file is an absolutely useless feature of Emacs that contributes very little to my configuration, if at all. This is because I use =straight.el= to manage my installed packages (something the custom file usually does) and you can set =custom-safe-themes= to =t=, removing the need to track what themes are trusted. And finally, if you use =M-x customize=, you're probably a psychopath.

This code works by sending the custom file to the =/tmp= directory, which is automatically cleared when you close your computer. Additionally, the file is never loaded, effectively removing it from existence.

#+begin_src emacs-lisp :tangle "init.el"
;; Disable the custom file by sending it to the temporary directory.
(setq custom-file (make-temp-file "emacs-custom-"))
#+end_src

** The =init.el= option to declare all themes as safe

Marks all themes as safe. I trust the devs :)
As a precaution, don't try lesser-known packages before vetting the code.

#+begin_src emacs-lisp :tangle "init.el"
(setq custom-safe-themes t)
#+end_src

** The =init.el= macro to configure a package (~my-emacs-configure~)

The ~my-emacs-configure~ is a simple wrapper around ~condition-case~. The idea is to add arbitrary code for the configuration of a given package and catch any errors so that Emacs can still load without that package's code.

#+begin_src emacs-lisp :tangle "init.el"
(defmacro my-emacs-configure (&rest body)
  "Evaluate BODY and catch any errors."
  (declare (indent 0))
  `(condition-case err
       (progn ,@body)
     ((error user-error quit)
      (warn "Failed to configure package starting with `%S' because of `%S'" (car ',body) (cdr err)))))
#+end_src

** The =init.el= minor mode for keybind overrides (~my-bind-overrides-mode~)

#+begin_src emacs-lisp :tangle "init.el"
(defvar my-bind-overrides-mode-map (make-sparse-keymap)
  "Keymap for `my-bind-overrides-mode'.")

(define-minor-mode my-bind-overrides-mode
  "Activate `my-bind-overrides-mode-map'."
  :global t
  :init-value nil
  :keymap my-bind-overrides-mode-map)
#+end_src

** The =init.el= loads my modules and libraries

#+begin_src emacs-lisp :tangle "init.el"
(mapc
 (lambda (string)
   (add-to-list 'load-path (locate-user-emacs-file string)))
 '("my-libraries" "my-modules"))
#+end_src

** The =init.el= second-last part to source the modules

I'm going to use Protesilaos as a reference once again and split my configuration into multiple files.

Splitting into multiple files allows me to review the individual source code files rather than searching through a large Org file.

#+begin_src emacs-lisp :tangle "init.el"
(require 'my-mod-theme)
(require 'my-mod-essentials)
(require 'my-mod-modeline)
(require 'my-mod-git)
(require 'my-mod-org)
(require 'my-mod-prog)
(require 'my-mod-text-editing)
(require 'my-mod-split-windows)
(require 'my-mod-completions)
(require 'my-mod-elfeed)
#+end_src

** The =init.el= final part to load keybind overrides (~my-bind-overrides-mode~)

#+begin_src emacs-lisp :tangle "init.el"
(my-bind-overrides-mode t)
#+end_src

* The modules in my configuration (=my-modules/=)

** The =my-mod-theme.el= module

*** TODO Implement theme picker

- Make it so you can change fonts on theme switch
- Add custom overrides for each theme

*** The =my-mod-theme.el= section to load themes

*Some Favourite Themes*:
- doric-dark
- doom-dark+
- doric-light

#+begin_src emacs-lisp :tangle "my-modules/my-mod-theme.el"
(my-emacs-configure
 (use-package doric-themes)
 (load-theme 'doric-obsidian))
#+end_src

*** The =my-mod-theme.el= section to load fonts

*Favourite Fonts*:
- =Iosevka=
- =Aporetic Sans/Serif Mono=
- =IBM Plex Mono=

#+begin_src emacs-lisp :tangle "my-modules/my-mod-theme.el"
(my-emacs-configure
 (set-face-font 'default "Aporetic Sans Mono 20")
 (set-face-font 'fixed-pitch "Aporetic Sans Mono 20")
 (set-face-font 'variable-pitch "Aporetic Sans 20"))
#+end_src

*** The =my-mod-theme.el= call to ~provide~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-theme.el"
(provide 'my-mod-theme)
#+end_src

** The =my-mod-essentials.el= module

To me, anything essential is anything that's vanilla Emacs that isn't terribly complicated.

*** The =my-mod-essentials.el= section for ~delete-selection-mode~

For some crazy reason, Emacs does not automatically delete your selection when you begin typing over it. This mode fixes that.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-essentials.el"
(my-emacs-configure
 (delete-selection-mode t))
#+end_src

*** The =my-mod-essentials.el= section for ~global-auto-revert-mode~

By default, Emacs will not update your buffer even if the underlying file is updated. This mode changes that.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-essentials.el"
(my-emacs-configure
  (global-auto-revert-mode 1)
  (setq auto-revert-verbose t))
#+end_src

*** The =my-mod-essentials.el= section for ~which-key-mode~

Emacs 30 added ~which-key-mode~, which gives you a list of the next keys you can press when you forget a key chord. For example, if I press =C-x= it will suggest =C-x 1= for ~delete-other-windows~.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-essentials.el"
(my-emacs-configure
 (setq which-key-separator "  "
       which-key-prefix-prefix "... "
       which-key-max-display-columns 3
       which-key-idle-delay 1.5
       which-key-idle-secondary-delay 0.25
       which-key-add-column-padding 1
       which-key-max-description-length 40)

 (which-key-mode 1))
#+end_src

*** The =my-mod-essentials.el= hook for ~delete-trailing-whitespace~

If you use ~auto-save-visited-mode~, you may find it annoying that your whitespaces keep getting involuntarily deleted. In such a case, I would recommend binding ~delete-trailing-whitespace~ to =C-x s= or whatever your save keybinding is.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-essentials.el"
(add-hook 'before-save-hook #'delete-trailing-whitespace)
#+end_src

*** The =my-mod-essentials.el= bind to ~duplicate-line~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-essentials.el"
(define-key my-bind-overrides-mode-map
            (kbd "C-,")
            (lambda ()
              (interactive)
              (duplicate-line)
              (next-line)))
#+end_src

*** The =my-mod-essentials.el= bind to ~grep-change-to-grep-edit-mode~

Writable ~grep-mode~ now comes built inside Emacs 31.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-essentials.el"
(my-emacs-configure
 (with-eval-after-load 'grep
   (define-key grep-mode-map (kbd "e") #'grep-change-to-wgrep-mode)))
#+end_src

*** The =my-mod-essentials.el= call to ~provide~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-essentials.el"
(provide 'my-mod-essentials)
#+end_src

** The =my-mod-modeline.el= module

#+begin_src emacs-lisp :tangle "my-modules/my-mod-modeline.el"
  (require 'my-lib-modeline)

  (setq display-time-string-forms '((format-time-string "%a %d %b, %H:%M")))
  (display-time-mode t)

  (setq-default mode-line-format
                (list
                 "  %e"
                 my-modeline-read-only
                 my-modeline-buffer-name
                 "  "
                 my-modeline-major-mode
                 'mode-line-process
                 "  "
                 my-modeline-vc
                 'mode-line-format-right-align
                 my-modeline-multiple-cursors
                 my-modeline-position
                 "  "
                 my-modeline-misc-info
                 "  "))
#+end_src

*** The =my-mod-modeline.el= call to ~provide~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-modeline.el"
(provide 'my-mod-modeline)
#+end_src

** The =my-mod-git.el= module

*** The =my-mod-git.el= section for =vc.el=

VC refers to "version control", which is what allows you to track your files and visualise changes across different versions of your data.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-git.el"
(my-emacs-configure
 (setq vc-follow-symlinks t)

 (with-eval-after-load 'vc
    ;; I only use Git.  If I ever need another, I will include it here.
    ;; This may have an effect on performance, as Emacs will not try to
    ;; check for a bunch of backends.
    (setq vc-handled-backends '(Git))

    (setq vc-dir-save-some-buffers-on-revert t)))
#+end_src

*** The =prot-emacs-git.el= section for ~magit~

Magit is an amazing package. It can basically do everything the builtin =vc.el= can do, and that's with no setup.
Start by pressing =C-x g= (~magit-status~) to bring up the state of the repository.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-git.el"
(my-emacs-configure
 (use-package magit))
#+end_src

*** The =my-emacs-git.el= call to ~provide~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-git.el"
(provide 'my-mod-git)
#+end_src

** The =my-mod-org.el= module

*** The =my-mod-org.el= section to setup ~org-mode~

I like to pull ~org-mode~ straight from the git mirror as to get the cutting-edge version.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-org.el"
(my-emacs-configure
 (use-package org
   :straight (:host github :repo "bzg/org-mode" :branch "main")
   :hook (org-mode . visual-line-mode)
   :custom
   (org-use-speed-commands t) ; M-x org-speed-commands-help
   (org-startup-indented t)
   (org-hide-emphasis-markers t)
   (org-cycle-separator-lines 1) ; Keep a line between folded headings
   (org-src-content-indentation 0)
   ))
#+end_src

*** The =my-mod-org.el= section for ~org-babel~

~Org-babel~ is what allows for literate configurations like this one.

~Org-tempo~ is very useful for Babel. It allows you to type something like =<el <TAB>= and it will expand into an Emacs Lisp codeblock.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-org.el"
(my-emacs-configure
  (org-babel-do-load-languages
  'org-babel-load-languages
  '((emacs-lisp . t)
    (shell . t)
    ))

 (require 'org-tempo)
 (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
 (add-to-list 'org-structure-template-alist '("sh" . "src shell")))
#+end_src

*** The =my-mod-org.el= section to fix "lexical binding" warning

*** The =my-mod-org.el= section for ~org-roam~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-org.el"
(my-emacs-configure
 (use-package org-roam
   :bind
   ("C-c n c" . org-roam-capture)
   ("C-c n f" . org-roam-node-find)
   ("C-c n i" . org-roam-node-insert)
   :custom (org-capture-bookmark nil)
   :config (org-roam-db-autosync-mode t))

 ;; ":commands" implies defer until the command is run
 (use-package org-roam-ui :commands org-roam-ui-mode))
#+end_src

*** The =my-mod-org.el= call to ~provide~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-org.el"
(provide 'my-mod-org)
#+end_src

** The =my-mod-prog.el= module

This module is to configure packages and parameters relevant to ~prog-mode~.

*When installing programming modes, use ~:defer t~ to avoid them loading preemptively.* I don't know if this does anything, but it's good to be safe.

*** The =my-mod-prog.el= section for ~eglot~ (LSP client)

~Eglot~ is a client for using LSP (Language Server Protocol) servers. I prefer it over ~lsp-mode~ because it is more lightweight and makes use of builtin Emacs features rather than implementing its own.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-prog.el"
(my-emacs-configure
 (use-package eglot
   :bind
   (:map eglot-mode-map
         ("C-c l a" . eglot-code-actions)
         ("C-c l r" . eglot-rename)
         ("C-c l f" . eglot-format))))
#+end_src

To enable an ~eglot~ for a specific mode, add the following to your configuration. Of course, you must have a supported language server installed first, but that's out of scope for this.

#+begin_example emacs-lisp
(add-hook 'SAMPLE-MAJOR-mode . #'eglot-ensure)
#+end_example

*** The =my-mod-prog.el= section for ~c++-mode~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-prog.el"
;; c++ mode is built in
(add-hook 'c++-mode #'eglot-ensure)
#+end_src

*** The =my-mod-prog.el= section for ~nix-mode~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-prog.el"
(my-emacs-configure
 (use-package nix-mode :defer t)
 (add-hook nix-mode-hook . eglot-ensure))
#+end_src

*** The =my-mod-prog.el= call to ~provide~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-prog.el"
(provide 'my-mod-prog)
#+end_src

** The =my-mod-text-editing= module

The idea for these keymaps is to keep your fingers on the =CTRL=, =META=, and =hjkl= keys for the majority of the time. The =,= and the =.= are also significant.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-text-editing.el"
(my-emacs-configure
 (use-package multiple-cursors
   :custom
   (mc/always-run-for-all t)
   :config
   (define-key my-bind-overrides-mode-map (kbd "C-M-j") #'mc/mark-all-dwim)
   (define-key my-bind-overrides-mode-map (kbd "C-M-/") #'mc/mark-all-like-this)

   (define-key my-bind-overrides-mode-map (kbd "C-M-,") #'mc/mark-previous-like-this)
   (define-key my-bind-overrides-mode-map (kbd "C-M-.") #'mc/mark-next-like-this)

   (define-key my-bind-overrides-mode-map (kbd "C-<") #'mc/skip-to-previous-like-this)
   (define-key my-bind-overrides-mode-map (kbd "C->") #'mc/skip-to-next-like-this)

   (define-key my-bind-overrides-mode-map (kbd "C-M-c") #'mc/edit-lines)
   (define-key my-bind-overrides-mode-map (kbd "C-M-n") #'mc/insert-numbers)
   (define-key my-bind-overrides-mode-map (kbd "C-M-'") #'mc-hide-unmatched-lines-mode))

 (use-package expreg
   :config
   (define-key my-bind-overrides-mode-map (kbd "C-M-l") #'expreg-expand)
   (define-key my-bind-overrides-mode-map (kbd "C-M-h") #'expreg-contract))

 (use-package move-text
   :config
   (define-key my-bind-overrides-mode-map (kbd "M-p") #'move-text-up)
   (define-key my-bind-overrides-mode-map (kbd "M-n") #'move-text-down)))
#+end_src

*** The =my-mod-text-editing= call to ~provide~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-text-editing.el"
(provide 'my-mod-text-editing)
#+end_src

** The =my-mod-split-windows= module

#+begin_src emacs-lisp :tangle "my-modules/my-mod-split-windows.el"
(my-emacs-configure
 (use-package golden-ratio
   :config
   (golden-ratio-mode t)
   (add-to-list 'golden-ratio-extra-commands 'ace-window))

 (use-package ace-window :config (define-key my-bind-overrides-mode-map (kbd "M-o") #'ace-window)))
#+end_src

*** The =my-mod-split-windows= call to ~provide~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-split-windows.el"
(provide 'my-mod-split-windows)
#+end_src

** The =my-mod-completions= module

*** The =my-mod-completions= sets variables for minibuffer

#+begin_src emacs-lisp :tangle "my-modules/my-mod-completions.el"
(savehist-mode t)
#+end_src

*** The =my-mod-completions= submodule for vertico

#+begin_src emacs-lisp :tangle "my-modules/my-mod-completions.el"
(my-emacs-configure
 (use-package vertico
   :config
   (vertico-mode)
   (vertico-multiform-mode)
   :custom
   (vertico-multiform-commands ; Customize display per-command
    '((execute-extended-command flat)))
   (vertico-resize t)
   (vertico-count 12)))
#+end_src

*** The =my-mod-completions= submodule for consult

I enjoy using =M-s= combined with another keybind in order to create lots of keybinds without using too many slots on the keyboard, and as a bonus it helps all the keybinds feel cohesive.

#+begin_src emacs-lisp :tangle "my-modules/my-mod-completions.el"
(my-emacs-configure
 (use-package consult
   :bind
   ("M-s M-g" . consult-ripgrep)
   ("M-s M-f" . find-file)
   ("M-s M-d" . consult-fd) ; Mnemonic: Search Directory
   ("M-s M-o" . consult-outline)
   ("M-s M-l" . consult-line)
   ("M-s M-b" . consult-buffer)
   ("M-s M-k" . kill-buffer)

   :config
   (setq consult-ripgrep-args "rg --null --line-buffered --color=never --max-columns=1000 --path-separator / --smart-case --no-heading --with-filename --line-number --search-zip --hidden"
         consult-fd-args "fd --full-path --color=never --hidden")

   ;; Don't display these buffers
   (let ((buffers '("*Async-native-compile-log*" "*straight-process*" "*straight-byte-compilation*" "*direnv*" "*Messages*" "*Help*" "*Backtrace*" "*Warnings*" "*Native-compile-Log" "*elfeed-tube-log*")))
     (dolist (buf buffers) (add-to-list 'consult-buffer-filter (regexp-quote buf))))
   (add-to-list 'consult-buffer-filter "\\*EGLOT.*\\*")
   (add-to-list 'consult-buffer-filter "magit.*:")))
#+end_src

*** The =my-mod-completions= submodule for miscellaneous minibuffer packages

#+begin_src emacs-lisp :tangle "my-modules/my-mod-completions.el"
(my-emacs-configure
 (use-package marginalia :config (marginalia-mode))

 (use-package orderless :config (setq completion-styles '(orderless basic)))

 (use-package embark
   :bind
   ("C-." . embark-act)
   (:map minibuffer-local-map
         ("C-c C-c" . embark-collect)
         ("C-c C-e" . embark-export)))

 (use-package embark-consult))
#+end_src

*** The =my-mod-completions= submodule for in-buffer completions

#+begin_src emacs-lisp :tangle "my-modules/my-mod-completions.el"
(my-emacs-configure
 (use-package corfu
   :custom
   (corfu-count 6)
   (corfu-auto-prefix 2)
   :init
   (global-corfu-mode)
   (corfu-popupinfo-mode)
   :hook (prog-mode . (lambda () (setq-local corfu-auto t)))
   :bind (:map corfu-map ("M-SPC" . corfu-insert-separator))))
#+end_src

*** The =my-mod-completions= call to ~provide~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-completions.el"
(provide 'my-mod-completions)
#+end_src

** The =my-mod-elfeed= module

*** The =my-mod-elfeed= base setup

#+begin_src emacs-lisp :tangle "my-modules/my-mod-elfeed.el"
(my-emacs-configure
 (use-package elfeed
   :bind ("C-x f" . elfeed)
   :hook (elfeed-show-mode . visual-line-mode)
   :custom (elfeed-search-filter "@6months +unread -junk"))

 (use-package elfeed-org
   :after elfeed
   :config (elfeed-org)))
#+end_src

*** The =my-mod-elfeed= ~elfeed-tube~ setup

#+begin_src emacs-lisp :tangle "my-modules/my-mod-elfeed.el"
(my-emacs-configure
 (use-package elfeed-tube
   :after elfeed
   :bind
   (:map elfeed-show-mode-map
         ("F" . elfeed-tube-fetch)
         ([remap save-buffer] . elfeed-tube-save))
   (:map elfeed-search-mode-map
         ("F" . elfeed-tube-fetch)
         ([remap save-buffer] . elfeed-tube-save))
   :config
   (elfeed-tube-setup)
   (add-hook 'elfeed-new-entry-hook
             (elfeed-make-tagger :entry-link "https://www\\.youtube\\.com/shorts/.*"
                                 :add 'junk
                                 :remove 'unread)))

 (use-package mpv)
 (use-package elfeed-tube-mpv
   :after elfeed
   :bind
   (:map elfeed-show-mode-map
         ("<return>" . elfeed-tube-mpv)
         ("C-c C-f" . elfeed-tube-mpv-follow-mode)
         ("C-c C-w" . elfeed-tube-mpv-where))))
#+end_src

*** The =my-mod-elfeed.el= call to ~provide~

#+begin_src emacs-lisp :tangle "my-modules/my-mod-elfeed.el"
(provide 'my-mod-elfeed)
#+end_src

* The libraries in my configuration (=my-libraries/=)

** The =my-lib-modeline.el= library

This library defines the icons, faces, and components of my modeline.

#+begin_src emacs-lisp :tangle "my-libraries/my-lib-modeline.el"
;;; prot-modeline.el --- Code for my custom mode line -*- lexical-binding: t -*-

(defvar my-modeline-icons
  '((dired-mode   "")
    (archive-mode "🮯")
    (diff-mode    "⇄")
    (prog-mode    "λ")
    (conf-mode    "")
    (text-mode    "¶")
    (comint-mode  "⨠")
    (t            "·")))

(defun my-modeline-get-icon ()
  (or
   (cadr (assq major-mode my-modeline-icons))
   (catch 'icon
     (dolist (entry my-modeline-icons)
       (when (and (not (eq (car entry) t)) (derived-mode-p (car entry)))
         (throw 'icon (cadr entry)))))
   (cadr (assq t my-modeline-icons))))

(defgroup my-modeline nil
  "Custom modeline that is stylistically close to the default."
  :group 'mode-line)

(defgroup my-modeline-faces nil
  "Faces for my custom modeline."
  :group 'my-modeline)

;; These blocks check if Emacs can display a sufficient amount of colors, and then checks if the theme is light or dark
(defface my-faces-red
  '((((class color) (min-colors 88) (background light)) :foreground "#aa3232")
    (((class color) (min-colors 88) (background dark)) :foreground "#f06464")
    (t :foreground "red"))
  "Use for red-colored icons"
  :group 'my-modeline-faces)

(defface my-faces-gray
  '((t :inherit (bold shadow)))
  "Use for gray-colored icons."
  :group 'my-modeline-faces)

(defvar my-modeline-read-only
  '(:eval
    (when buffer-read-only
      (propertize
       " "
       'face (if (mode-line-window-selected-p)
                 'my-faces-red
               'my-faces-gray)))))

(defvar my-modeline-buffer-name
  '(:eval
    (propertize (buffer-name) 'face
                (if (buffer-modified-p)
                    '(:weight bold :slant italic) 'bold))))

(defvar my-modeline-major-mode
  '(:eval
    (format "%s %s"
            (propertize (my-modeline-get-icon) 'face 'my-faces-gray)
            (capitalize (string-replace "-mode" "" (symbol-name major-mode))))))

(defvar my-modeline-vc
  '(:eval
    (when (mode-line-window-selected-p)
      (unless (not vc-mode)
        (let ((s (substring-no-properties vc-mode 5)))
          (concat
           (propertize "⇅ " 'face 'my-faces-gray)
           (if (eq (vc-state buffer-file-name) 'up-to-date)
               s
             (propertize s 'face 'italic))))))))

(defvar my-modeline-multiple-cursors
  '(:eval
    (when (and (mode-line-window-selected-p) (bound-and-true-p multiple-cursors-mode))
      mc/mode-line)))

(defvar my-modeline-position
  '(:eval
    (when (mode-line-window-selected-p)
      (format-mode-line "%6l:%c (%%p)"))))

(defvar my-modeline-misc-info
  '(:eval
    (when (mode-line-window-selected-p)
      (format-mode-line mode-line-misc-info))))

(provide 'my-lib-modeline)
#+end_src
